### ISSUE TITLE
ReferenceErrors in browserless environment

### ISSUE THREAD

**Issue by sgreav** [eligrey/l10n.js#34]
An issue occurs when L10N is being used in a browserless environment, such as being run directly using Node. 

The issues largely come from the assumption that certain objects will exist, such as `self`, `XMLHttpRequest` and `document`, with the former two causing ReferenceErrors when they are reached in the code. This is particularly a problem when it comes to running Unit Tests on localization code inside environments like Mocha.

The errors in question are as follows: 

`ReferenceError: self is not defined
 at l10n.js:20:9`

and 

`ReferenceError: XMLHttpRequest is not defined
 at l10n.js:196:11`

I have a proposed set of changes to fix this issue for Node that I can create a PR for, if it is considered something that is in scope for the library to handle.

**Comment by eligrey** [comment]
Sure, I'm open to PRs.

**Comment by sgreav** [comment]
Excellent, thanks Eli. I will make the PR and link it here.
